### ISSUE TITLE
Hide to tray is not working with XFCE virtual desktop setups

### ISSUE THREAD

**Issue by ghost** [psi-plus/main#669] opened 2016-12-22 16:39 UTC
Under following conditions hiding to tray by clicking tray icon is no longer working. However, selecting appropriate item ("Hide") from context menu is still working.
0. Open psi-plus on virtual desktop number 1.
1. Open some application (e.g. chromium or gnome-terminal) on another virtual desktop (number 2) in fullscreen mode.
2. Hiding to tray is now broken until application on virtual desktop 2 quits fullscreen mode.
With other applications like thunderbird hiding to tray is still working so I classifying it as psi-plus's bug.
DE: Xfce
WM: Xfwm4
Distro: Ubuntu 16.04
Psi-plus version: v0.16.568.604 (2016-10-22)

**Comment by nekomiko** [comment] 2017-01-07 11:34
I strongly suspect that this bug is WM-dependent.

**Comment by Ri0n** [comment] 2017-01-09 15:37
What's your Qt version? (check this in help menu of Psi)

**Comment by nekomiko** [comment] 2017-01-09 20:03
I'm using psi-plus from ppa:psi-plus/ppa on ubuntu xenial. Qt version is 4.8.7.

**Comment by Ri0n** [comment] 2017-01-09 20:16
Hm I have tray problem on Xenial too. But different and with Qt 5.6.
It even does not show up in tray. Sometimes some blank space is added.

If I use aproximatelly the same configuration on Gentoo Linux tray works perfect even when I have something in full screen on second monitor.

But all of this is on KDE.
Xfce still uses Xembed tray implementation AFAIK. Xembed tray always worked good. So I can't say what could be wrong. I'll test when I have time for this.

**Comment by nekomiko** [comment] 2017-01-09 22:45
>I have something in full screen on second monitor.
Not exactly this. Second monitor is working fine. Virtual desktop (workspace) is the problem.

**Comment by nekomiko** [comment] 2017-01-11 00:27
I built from git with Qt 5.5.1 and problem remains.

**Comment by nekomiko** [comment] 2017-01-14 03:59
>Xfce still uses Xembed tray implementation AFAIK.
Appindicator is also supported in latest xubuntu.

**Comment by nekomiko** [comment] 2017-01-31 15:21
>But all of this is on KDE.
It works on KDE for me too. Should be XFCE-specific.

**Comment by nekomiko** [comment] 2017-03-02 08:56
Problem still remains for me with Psi+ v0.16.572.639-webkit (2017-02-27)  Qt 5.5.1 on Xfce4

**Comment by Ri0n** [comment] 2018-01-02 11:18
I was able to reproduce the issue with xfce.
qt-5.10.

broken in Psi+ only. 
Psi works fine.

**Comment by Ri0n** [comment] 2018-01-02 12:06
most likely 0120-psi-tray-act-bring-to-front.diff breaks things returning invalid result from X11WindowSystem::isWindowObscured

**Comment by Vitozz** [comment] 2018-01-02 12:07
Delete this useless patch

**Comment by Ri0n** [comment] 2018-01-02 13:20
The reason why this patch at all exists https://code.google.com/archive/p/psi-dev/issues/300

**Comment by Ri0n** [comment] 2018-01-02 15:10
as a workaround, just disable options.ui.contactlist.raise-inactive option.

**Comment by Ri0n** [comment] 2018-01-02 20:38
fixed by d911875c8034f48b2ae477919b2eabfdc0d6f60e

**Closed by Ri0n** 2018-01-02 20:38 UTC
