### ISSUE TITLE
Significant memory usage when many hunspell dictionaries are available

### ISSUE THREAD

**Issue by formusiclgl** [psi-plus/main#695] opened 2017-09-25 10:06 UTC
Hello! Psi+ v1.2.75 (2017-09-12, Psi:f78fd0ec, Psi+:43fb3ea) Win7 sp1 x64. Psi+ take 530 MB RAM, is it normal ?

**Comment by Ri0n** [comment] 2017-09-25 20:39
how many contacts do you have? Do you see memory usage growing in a hour/day?

**Comment by formusiclgl** [comment] 2017-09-26 08:01
4 contacts, RAM allocate may change +- 20-30 MB

**Comment by Ri0n** [comment] 2017-09-26 08:20
I see 38M consumption with official release and 300 contacts.
If you use portable build you have to manually remove everything useless from myspell/dicts otherwise all of them will be loaded taking a lot of memory.

**Comment by formusiclgl** [comment] 2017-09-27 07:11
After clearing myspell/dicts consumption is ok.

**Comment by tehnick** [comment] 2017-09-27 08:38
And what may I do in this case? Do you suggest to delete all languages besides six chosen ones (as done in builds from KukuRuzo)? This is discrimination of other users...

BTW, Which language for spell checking is default in settings? Hunspell should not load all available languages, if only one or few languages are selected.

**Comment by Ri0n** [comment] 2017-09-27 09:02
I honestly don't know. There are many ways to solve this.
- Some setup script to remove not needed discts
- Load only relevant (requires kind of database what could be relevant for each country. like Russian in Ukraine)
- Default settings in psi to just relevant and gui for manual selection
- Online portable-build constructor
- Download dictionaries in runtime may be even by autodetection of input language.

What we need is the idea which will satisfy the majority.
But currently installer has language selector and the problem is related to portable builds.

**Comment by formusiclgl** [comment] 2017-09-27 09:07
In setting->application->language is By default. I cannot find spell checking language settings. Acceptable variant like Firefox do. Right mouse button click on input field->spell checking->choose language. 
At first time load only relevant by setting->application->language

**Comment by Ri0n** [comment] 2017-09-27 09:20
I believe Firefox also has not trivial logic behind.
For example it offers me to select Spanish while my system has no Spanish dicts. I guess it collects some stats somehow and offers relevant based on them.
In Psi we can always load English (as a very popular language) and some others based on current locale and selected language for interface. But put them all in the menu like in Firefox not the good idea. There are too many languages. Nevertheless I like how it's done in Firefox.

PS I learn Spanish

**Comment by formusiclgl** [comment] 2017-09-27 09:36
> There are too many languages
Yes. If you installed many languages in Firefox, so there will be many languages too.
So 
1. Download dictionaries in runtime (like Firefox)
or
2. Spell checking language settings with check boxes + Right mouse button click on input field->spell checking->choose language (from checked items in Spell checking language settings)

**Comment by tehnick** [comment] 2017-09-27 09:43
> I cannot find spell checking language settings.

Settings dialog --> Advanced --> options --> ui --> spell-check --> langs (use short language names and comma as a separator, for example "ru,en")

**Comment by formusiclgl** [comment] 2017-09-27 10:11
Thank you! it's hard to find

**Comment by formusiclgl** [comment] 2017-09-27 10:12
I have empty Settings dialog --> Advanced --> options --> ui --> spell-check --> langs

**Comment by tehnick** [comment] 2017-09-27 10:12
I have just checked in WinXP: the amount of memory used by Psi+ does not depend on value of `langs` variable in settings. It looks like a bug in our usage of hunspell.

**Comment by tehnick** [comment] 2017-09-27 10:32
More over, after deleting of `myspell` subdirectory Psi+ launches and connects to xmpp servers almost momentary. So it is definitely a bug and serious one.

**Comment by tehnick** [comment] 2017-09-30 14:11
Added a simple workaround to all portable builds. See `available-dicts` subdirectory and `ReadMe.dictionaries.txt`.

**Comment by formusiclgl** [comment] 2017-09-30 16:28
If you move ReadMe.dictionaries.txt to folder with psi-plus-portable.exe more then 1 people will read it ^)

**Comment by tehnick** [comment] 2017-10-02 15:39
@formusiclgl This is only a temporary workaround. KukuRuzo is working on real solution now.

**Comment by tehnick** [comment] 2017-10-05 09:32
Fixed in b7f8ecdb8864f4a88a97c37672aecb986cbf6578

**Closed by tehnick** 2017-10-05 09:32 UTC
Labels: Bug
