### ISSUE TITLE
Remembered XMPP password is wrong

### ISSUE THREAD

**Issue by marak8** [psi-plus/main#705] opened 2018-01-19 23:40 UTC
Hi.

Recently I've updated psi-plus on my ArchLinux box

    [2018-01-17 22:22] [ALPM] upgraded psi-plus (1.2.154-1 -> 1.2.164-1)

since then, whenever I start it opens a popup asking me for the password to my Jabber account. The popup has title _Wrong Account Password_. I always check that I want to remember the password but it doesn't make any difference. I've also tried to change the password while connected and restart psi-plus but on every connect it asks for correct password.

**Comment by Ri0n** [comment] 2018-01-20 04:23
It seems keyring mánager is not started on your system. 
So you can use insecure password storage by disabling keyring un Psi settings

**Comment by rapgro** [comment] 2018-01-20 10:19
Related to #692 then.

**Comment by marak8** [comment] 2018-01-20 10:48
That's a good point. I do not run `gnome-keyring-daemon`. But previously (with `1.2.154-1`) it worked automatically without it. However, even I the keyring daemon is running, it seems Psi doesn't store password into it and still ask for the password.

**Comment by Ri0n** [comment] 2018-01-20 16:44
daemon version? console logs?

**Comment by marak8** [comment] 2018-01-22 21:01
I couldn't find where gnome-keyring-logs are. It creates some socket files under `/run/user/1000/keyring/` but according to lsof, they're not used by any process. Don't know what's happening there.


	user@localhost ~ % pacman -Qo =gnome-keyring-daemon
	/usr/bin/gnome-keyring-daemon is owned by gnome-keyring 1:3.27.2-1
	user@localhost ~ % pacman -Qo =psi-plus
	/usr/bin/psi-plus is owned by psi-plus 1.2.164-1

	user@localhost ~ % psi-plus
	[20180122 21:57:40] W:PsiIconset::Private::iconsetPath("roster/crystal-msn.jisp"): not found (unknown:0, unknown)
	[20180122 21:57:40] W:PsiIconset::Private::iconsetPath("roster/crystal-aim.jisp"): not found (unknown:0, unknown)
	[20180122 21:57:40] W:libpng warning: iCCP: known incorrect sRGB profile (unknown:0, unknown)
	[20180122 21:57:40] Theme server is started at  QUrl("http://127.0.0.1:44437") (unknown:0, unknown)
	[0122/215740.553978:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/user/#11935826 (deleted)
	  Error: No such file or directory
	[20180122 21:57:40] Starting loading "psi/classic" theme at "/usr/share/psi-plus/themes/chatview/psi/classic" for chat (unknown:0, unknown)
	[20180122 21:57:40] Starting loading "psi/classic" theme at "/usr/share/psi-plus/themes/chatview/psi/classic" for muc (unknown:0, unknown)
	[20180122 21:57:40] W:libpng warning: iCCP: known incorrect sRGB profile (unknown:0, unknown)
	[20180122 21:57:40] W:libpng warning: iCCP: known incorrect sRGB profile (unknown:0, unknown)
	[20180122 21:57:40] W:libpng warning: iCCP: known incorrect sRGB profile (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  794 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  794 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  794 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  794 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  794 (unknown:0, unknown)
I couldn't find where gnome-keyring-daemon logs are.

	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Unknown signature value:  795 (unknown:0, unknown)
	[20180122 21:57:40] Util is initilizing (unknown:0, unknown)
	[20180122 21:57:40] Psi adapter is ready (unknown:0, unknown)
	[20180122 21:57:40] Util successfully initialized (unknown:0, unknown)
	[20180122 21:57:40] Util is initilizing (unknown:0, unknown)
	[20180122 21:57:40] psi/classic theme is successfully loaded for muc (unknown:0, unknown)
	[20180122 21:57:40] Psi adapter is ready (unknown:0, unknown)
	[20180122 21:57:40] Util successfully initialized (unknown:0, unknown)
	[20180122 21:57:40] psi/classic theme is successfully loaded for chat (unknown:0, unknown)
	[20180122 21:57:41] unexpected version response (unknown:0, unknown)
	[20180122 21:57:42] W:KeyChain error=5 (unknown:0, unknown)

**Comment by Vitozz** [comment] 2018-01-23 14:02
In ps-plus-git from AUR there is no such problems
$ pacman -Qo gnome-keyring-daemon
/usr/bin/gnome-keyring-daemon принадлежит gnome-keyring 1:3.27.2-1
$ pacman -Qo psi-plus
/usr/bin/psi-plus принадлежит psi-plus-git 1.2.171.0.g335bcccb-1

**Comment by Ri0n** [comment] 2018-01-24 05:17
This is the error 5 from /usr/include/qt5keychain/keychain.h
`NoBackendAvailable, /**< No platform-specific keychain service available */`

I don't quite understand what does it mean. May be authors of qt5keychain know better

**Comment by Ri0n** [comment] 2018-02-14 09:25
Well, since it works fine for @Vitozz (same system), I believe the problem is in some system misconfiguration.
I suggest to get some advice from qtkeychain developers.
For now I am closing this issue.

**Closed by Ri0n** 2018-02-14 09:25 UTC
