### ISSUE TITLE
[Multirows] Pinned tabs do not wrap to the next line in multiline mode

### ISSUE THREAD

**Issue by Neustradamus** [psi-plus/main#743] opened 2019-01-01 12:47 UTC
A pinned tab in the first line is not complete, next completely hidden, the next in the second line....
- https://i.ibb.co/7XzCK12/psi-plus-multirows-bug.png

**Comment by Vitozz** [comment] 2019-02-26 10:08
This is not a bug, this behavior was intended by the developer. But I think it can be corrected by making all the text visible.

**Comment by Vitozz** [comment] 2019-03-03 21:58
As I see bug was fixed. Please check and close the issue

**Comment by Neustradamus** [comment] 2019-03-04 10:41
Yes the problem has been fixed with the first ticket.
-> https://github.com/psi-plus/main/issues/741

**Closed** 2019-03-04 11:47 UTC

**Comment by Neustradamus** [comment] 2020-03-28 17:54
@ri0n: I think, it can be moved to @psi-im/psi.
Thanks in advance.
